print("Nume:                                Bejan Angela")
print("Data si locul nasterii:              22.03.205 Balti")
print("E-mail:                              angelikabejan@gmail.com")
print("Telefon:                             079309198")
print("Adresa:                              Lesecico 16,scara 2, ap.37")
print("Nationalitate:                       moldoveanca")
print("Studii:                              Institutia Publica Liceul Teoretic Mihai Eminescu")
print("Limba materna:                       limba romina")
print("Limbi straine:                       engleza:incepator, franceza:incepator, rusa:mediu")
print("Competente si abilitati sociale:     lucru in echipa")
print("Aptitudini:                          comunicabila, responsabila, ambitioasa")
print("Hobby:                               dansurile, tenis de camp")